#!/usr/bin/env node
"use strict";
const fs = require("node:fs");
const path = require("node:path");
function read(file) { return JSON.parse(fs.readFileSync(path.resolve(file), "utf8")); }
function clean(value) { return String(value ?? "").trim(); }
function id(value) { return clean(value).toLowerCase().replace(/[^a-z0-9а-яё]+/gi, "-").replace(/^-|-$/g, "") || "item"; }
function anchorValue(anchor) { if (typeof anchor === "string") { const match = anchor.match(/^(.*):(\d+)$/); return match ? { file: match[1], line: Number(match[2]) } : { scope: anchor }; } return anchor || {}; }
function main() {
  const args = process.argv.slice(2), get = (flag) => args[args.indexOf(flag) + 1];
  const legacy = read(get("--legacy-request")), stage1File = get("--stage1"), stage2File = get("--stage2"), stage3File = get("--stage3"), stage4File = get("--stage4"), stage5File = get("--stage5"), stage6File = get("--stage6"), stage1 = read(stage1File), stage2 = read(stage2File), stage3 = read(stage3File), stage4 = read(stage4File), stage5 = read(stage5File), stage6 = read(stage6File), output = get("--output");
  if (!output) throw new Error("Provide --output <stage-7-request.json>");
  const evidenceIndex = [], evidenceIds = new Set();
  function evidence(prefix, row, anchors) { const refs = []; const values = Array.isArray(anchors) && anchors.length ? anchors : [row.scope || row.searchScope || row.result || row.id]; values.forEach((anchor, index) => { let key = `evidence:${id(prefix)}:${index + 1}`; let suffix = 1; while (evidenceIds.has(key)) key = `evidence:${id(prefix)}:${index + 1}-${++suffix}`; evidenceIds.add(key); evidenceIndex.push({ id: key, ...anchorValue(anchor), result: row.result || row.consequence || row.role || row.relation || "recorded evidence" }); refs.push(key); }); return refs; }
  const confirmedUsages = (legacy.confirmedUsages || []).map((row) => ({ ...row, status: "confirmed", evidenceRefs: evidence(`usage-${row.id}`, row, row.anchors) }));
  const checkedNoUsage = (legacy.checkedNoUsage || []).map((row) => ({ ...row, status: "checked-no-usage", searchScope: typeof row.scope === "string" ? row.scope : JSON.stringify(row.scope || {}), evidenceRefs: evidence(`absence-${row.id}`, row, []) }));
  const referenceOnly = (legacy.referenceOnly || []).map((row) => ({ ...row, status: "reference-only", evidenceRefs: evidence(`reference-${row.id}`, row, row.anchors) }));
  const ownership = ((stage1.ownership || {}).groups || []).map((row) => ({ id: `ownership:${id(row.id)}`, name: row.object, role: row.role, relation: row.relation, order: row.order, status: row.status, evidenceRefs: evidence(`ownership-${row.id}`, row, row.anchor ? [row.anchor] : []) }));
  const graphEdges = ((stage2.ownershipGraph || {}).edges || []);
  const dictionary = ((stage2.ownershipGraph || {}).nodes || []).map((row) => ({ id: `dictionary:${id(row.id)}`, term: row.entity, role: row.role, order: row.order, status: row.status === "confirmed" ? "confirmed" : "partial", relations: graphEdges.filter((edge) => edge.from === row.id || edge.to === row.id).map((edge) => `${edge.from} ${edge.relation} ${edge.to}`).sort(), anchors: row.anchors || [] }));
  const stage3Checks = new Map((((stage3.sourceEvidence || {}).checks) || []).map((check) => [check.id, check]));
  const scenarios = (stage3.consumerCoverage || []).map((row) => { const check = stage3Checks.get(row.checkId); const refs = evidence(`scenario-${row.boundaryId}-${row.consumerRepo}`, { result: `consumer coverage: ${row.status}` }, check ? (check.fullMatches || check.matches || []).slice(0, 5).map((match) => ({ file: match.file, line: match.line, symbol: match.patternId, result: match.snippet })) : [row.scope]); return { id: `scenario:${id(row.boundaryId)}:${id(row.consumerRepo)}`, name: `${row.boundaryId} -> ${row.consumerRepo}`, status: row.status === "verified" ? "confirmed" : "partial", scope: row.scope, checkId: row.checkId, evidenceRefs: refs }; });
  const stage4Checks = new Map((((stage4.sourceEvidence || {}).checks) || []).map((check) => [check.id, check]));
  const recipientFamilies = (stage4.recipientFamilies || []).map((row) => { const matches = (row.checkIds || []).flatMap((checkId) => { const check = stage4Checks.get(checkId); return check ? (check.fullMatches || check.matches || []).slice(0, 5) : []; }); const refs = evidence(`recipient-${row.id}`, { result: `${row.totalMatches || 0} source matches; ${row.relation}` }, matches.map((match) => ({ file: match.file, line: match.line, symbol: match.patternId, result: match.snippet }))); return { id: `recipient:${id(row.id)}`, name: row.receiver, relation: row.relation, status: matches.length ? "confirmed" : "partial", totalMatches: row.totalMatches, checkIds: row.checkIds, evidenceRefs: refs, metadata: row.metadata }; });
  const criticalPaths = (((stage5.sourceEvidence || {}).checks) || []).map((row) => ({ id: `path:${id(row.id)}`, name: row.id, status: row.totalMatches > 0 ? "confirmed" : "unknown", evidenceRefs: evidence(`path-${row.id}`, { result: `${row.totalMatches || 0} source matches` }, (row.fullMatches || row.matches || []).slice(0, 3).map((match) => ({ file: match.file, line: match.line, symbol: match.patternId, result: match.snippet }))) }));
  const surfaceEvidence = new Map((stage6.sourceSurfaces || []).map((row) => [row.path, evidence(`surface-${row.path}`, { result: `${row.layer}: ${row.role}` }, [{ file: row.path, result: `${row.role}; changed=${row.changed}; patchSha256=${row.patchSha256}` }])]));
  const referencePaths = (stage6.sourceSurfaces || []).map((row) => ({ id: `reference-path:${id(row.path)}`, name: row.role, path: row.path, layer: row.layer, changed: row.changed, patchSha256: row.patchSha256, status: "reference-only", evidenceRefs: surfaceEvidence.get(row.path) }));
  const gaps = checkedNoUsage.map((row) => ({ id: `gap:${id(row.id)}`, title: row.reason || row.result || row.id, status: "checked-no-usage", evidenceRefs: row.evidenceRefs, expectedNames: row.expectedNames, searchScope: row.searchScope, consequence: row.consequence }));
  const implementationEntryPoints = (stage6.sourceSurfaces || []).map((row) => ({ id: `entry:${id(row.path)}`, title: row.role, path: row.path, layer: row.layer, status: "reference-only", evidenceRefs: surfaceEvidence.get(row.path), gapRefs: gaps.filter((gap) => clean(gap.searchScope).includes(row.path) || clean(gap.title).toLowerCase().includes(clean(row.layer).toLowerCase())).map((gap) => gap.id) }));
  const limitationTexts = [...(legacy.openChecks || []), ...(stage6.openChecks || [])];
  const limitations = [...new Set(limitationTexts.map(clean).filter(Boolean))].sort().map((text, index) => ({ id: `limitation:${index + 1}`, status: "partial", description: text }));
  const noise = (legacy.noise || []).map((row, index) => ({ ...row, id: row.id || `noise:${index + 1}`, status: "noise" }));
  const priorArtifacts = [stage1File, stage2File, stage3File, stage4File, stage5File, stage6File].map((file) => path.resolve(file));
  const request = { stage: 7, inventoryId: `inventory:${id(legacy.target)}:v4`, target: legacy.target, scope: legacy.scope, priorArtifacts, provenance: { migration: "legacy-stage7-request+stage1/2/3/4/5/6-facts", sourceStages: [1, 2, 3, 4, 5, 6] }, executiveSummary: { purpose: "Полная каноническая модель инвентаризации внутренних теней", limitationCount: limitations.length }, decisionStatus: limitations.length ? "partial" : "confirmed", ownership, dictionary, scenarios, recipientFamilies, criticalPaths, referencePaths, gaps, implementationEntryPoints, confirmedUsages, checkedNoUsage, referenceOnly, noise, limitations, evidenceIndex, capabilities: legacy.capabilities || [], stageExecution: { completedStages: [0, 1, 2, 3, 4, 5, 6, 7], stage7Contract: "inventory-report-model/1.0.0" }, renderProfile: { documents: ["decision-report", "implementation-map", "evidence"] }, openChecks: [], transition: { "next stage": "8" } };
  fs.writeFileSync(path.resolve(output), `${JSON.stringify(request, null, 2)}\n`, "utf8");
  process.stdout.write(`${JSON.stringify({ status: "ok", output: path.resolve(output), counts: { evidence: evidenceIndex.length, usages: confirmedUsages.length, absences: checkedNoUsage.length, ownership: ownership.length, dictionary: dictionary.length, recipients: recipientFamilies.length, paths: criticalPaths.length, gaps: gaps.length, limitations: limitations.length } })}\n`);
}
try { main(); } catch (error) { process.stdout.write(`${JSON.stringify({ status: "error", errors: [{ message: error.message }] })}\n`); process.exitCode = 2; }
