#!/usr/bin/env node
"use strict";
const fs = require("node:fs");
const path = require("node:path");
const { canonicalJson, validateReportModel, withoutIntegrity } = require("./report_model");
function projection(model) { return withoutIntegrity(model); }
function compareStage7Facts(baseline, candidate) { const baselineValidation = validateReportModel(baseline), candidateValidation = validateReportModel(candidate); const equal = baselineValidation.ok && candidateValidation.ok && canonicalJson(projection(baseline)) === canonicalJson(projection(candidate)); return { schemaVersion: "1.0.0", gate: "stage7-report-model-equivalence", status: equal ? "equivalent" : "not-equivalent", validation: { baseline: baselineValidation.ok, candidate: candidateValidation.ok }, digests: { baseline: baseline.integrity?.canonicalDigest || null, candidate: candidate.integrity?.canonicalDigest || null } }; }
function main() { try { const args = process.argv.slice(2), get = (flag) => { const index = args.indexOf(flag); return index >= 0 ? args[index + 1] : undefined; }, baselineFile = get("--baseline"), candidateFile = get("--candidate"); if (!baselineFile || !candidateFile) throw new Error("Provide --baseline <report-model.json> --candidate <report-model.json>"); const result = compareStage7Facts(JSON.parse(fs.readFileSync(path.resolve(baselineFile))), JSON.parse(fs.readFileSync(path.resolve(candidateFile)))); const output = get("--output"); if (output) fs.writeFileSync(path.resolve(output), canonicalJson(result)); process.stdout.write(`${JSON.stringify({ gate: result.gate, status: result.status, validation: result.validation, digests: result.digests, output: output ? path.resolve(output) : null })}\n`); if (result.status !== "equivalent") process.exitCode = 1; } catch (error) { process.stdout.write(`${JSON.stringify({ status: "error", errors: [{ message: error.message }] })}\n`); process.exitCode = 2; } }
if (require.main === module) main();
module.exports = { compareStage7Facts, projection };
