#!/usr/bin/env node
"use strict";
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { canonicalJson, validateReportModel } = require("./report_model");
function esc(value) { return String(value ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, " "); }
function table(headers, rows) { return [`| ${headers.join(" | ")} |`, `| ${headers.map(() => "---").join(" | ")} |`, ...rows.map((row) => `| ${row.map(esc).join(" | ")} |`)].join("\n"); }
function explanation(shows, purpose) { return `Что показывает: ${shows}\n\nЗачем нужна: ${purpose}\n\nКак читать: каждая строка имеет стабильный идентификатор и статус.\n\nКак использовать: переходить по идентификаторам к детальной доказательной базе.`; }
function refs(row) { return (row.evidenceRefs || []).join(", "); }
function section(title, shows, purpose, headers, rows) { return `## ${title}\n\n${explanation(shows, purpose)}\n\n${table(headers, rows)}\n`; }
function renderDecision(model) {
  const counts = [["Подтверждённые использования", model.confirmedUsages.length], ["Семейства получателей", model.recipientFamilies.length], ["Критические пути", model.criticalPaths.length], ["Пробелы", model.gaps.length], ["Точки реализации", model.implementationEntryPoints.length], ["Ограничения", model.limitations.length], ["Evidence", model.evidenceIndex.length]];
  const usages = model.confirmedUsages.map((x) => [x.id, x.title || x.name || x.role || "Подтверждённое использование", x.result || "", x.status, refs(x)]);
  const gaps = model.gaps.map((x) => [x.id, x.title || x.description || "Пробел", (x.expectedNames || []).join(", "), x.searchScope || "", x.status, refs(x)]);
  const limitations = model.limitations.map((x) => [x.id, x.description || x.title || "", x.status]);
  const capabilities = model.capabilities.map((x) => [x.id, x.status, (x.evidenceRefs || []).join(", "), x.requiredForFinalReport ? "да" : "нет"]);
  return `# Инвентаризация: ${esc(model.target)}\n\n## Общая картина\n\nСтатус решения: **${esc(model.decisionStatus)}**. Модель Stage 7 закрыта, обязательных открытых проверок: ${model.openChecks.length}. Статус partial означает сохранённые ограничения, а не потерю строк отчёта.\n\n${section("Масштаб исследования", "количественный охват модели", "позволяет быстро оценить полноту и размер blast radius", ["Область", "Количество"], counts)}\n${section("Подтверждённые использования", "основные подтверждённые использования", "даёт краткую картину фактического охвата", ["ID", "Использование", "Результат", "Статус", "Доказательства"], usages)}\n${section("Пробелы и решения", "проверенные пробелы", "поддерживает принятие решения о доработке", ["ID", "Пробел", "Ожидаемые имена", "Область", "Статус", "Доказательства"], gaps)}\n${section("Ограничения", "границы достоверности отчёта", "не позволяет принять ограничение за подтверждённый факт", ["ID", "Ограничение", "Статус"], limitations)}\n${section("Покрытие возможностей", "обязательные аспекты инвентаризации", "показывает, какими доказательствами закрыта каждая capability", ["Capability", "Статус", "Доказательства", "Обязательна"], capabilities)}\n## Переход к деталям\n\n- [Карта реализации](implementation-map.md) — ownership, словарь, сценарии, получатели, пути и точки изменения.\n- [Доказательная база](evidence.md) — полный индекс source evidence, отсутствие использования, эталоны и шум.\n`;
}
function renderImplementation(model) {
  const ownership = model.ownership.map((x) => [x.id, x.name || x.object || "", x.order ?? "", x.role || "", x.relation || "", x.status, refs(x)]);
  const dictionary = model.dictionary.map((x) => [x.id, x.term || x.name || "", x.order ?? "", (x.relations || []).join("; "), x.status]);
  const scenarios = model.scenarios.map((x) => [x.id, x.name || "", typeof x.scope === "string" ? x.scope : JSON.stringify(x.scope || {}), x.status, refs(x)]);
  const recipients = model.recipientFamilies.map((x) => [x.id, x.name || x.title || "Получатель", x.relation || "", x.totalMatches ?? "", x.status, refs(x)]);
  const paths = model.criticalPaths.map((x) => [x.id, x.name || x.title || "Путь", x.status || "unknown", refs(x)]);
  const references = model.referencePaths.map((x) => [x.id, x.layer || "", x.path || "", x.name || "", x.status, refs(x)]);
  const entries = model.implementationEntryPoints.map((x) => [x.id, x.layer || "", x.path || "", x.title || "", (x.gapRefs || []).join(", "), x.status, refs(x)]);
  return `# Карта реализации: ${esc(model.target)}\n\n${section("Владение", "цепочку владения сущностью", "показывает, где хранится и передаётся состояние", ["ID", "Объект", "Порядок", "Роль", "Связь", "Статус", "Доказательства"], ownership)}\n${section("Словарь и переходы имён", "объекты и связи, расширившие поиск", "помогает проследить переход между слоями", ["ID", "Термин", "Порядок", "Связи", "Статус"], dictionary)}\n${section("Сценарии", "пользовательские и технические старты", "показывает границы подтверждённых переходов", ["ID", "Сценарий", "Область", "Статус", "Доказательства"], scenarios)}\n${section("Получатели", "семейства получателей", "показывает blast radius", ["ID", "Получатель", "Связь", "Совпадения", "Статус", "Доказательства"], recipients)}\n${section("Критические пути", "сквозные пути механизма", "показывает границы реализации и разрывы", ["ID", "Путь", "Статус", "Доказательства"], paths)}\n${section("Эталонные пути", "существующие соседние механизмы", "показывает, с чем сравнивать доработку", ["ID", "Слой", "Путь", "Роль", "Статус", "Доказательства"], references)}\n${section("Существующие точки входа для доработки", "конкретные существующие места изменения", "связывает пробелы с реализацией", ["ID", "Слой", "Путь", "Роль", "Пробелы", "Статус", "Доказательства"], entries)}\n`;
}
function renderEvidence(model) {
  const evidence = model.evidenceIndex.map((x) => [x.id, x.file || (typeof x.scope === "string" ? x.scope : JSON.stringify(x.scope || {})), x.line || "", x.symbol || x.anchor || "", x.result || x.summary || ""]);
  const usages = model.confirmedUsages.map((x) => [x.id, x.role || x.title || "", x.result || "", x.consequence || "", refs(x)]);
  const absence = model.checkedNoUsage.map((x) => [x.id, (x.expectedNames || []).join(", "), x.reason || "", x.searchScope || x.scope || "", x.result || "", x.consequence || "", refs(x)]);
  const references = model.referenceOnly.map((x) => [x.id, x.relation || "", x.consequence || "", refs(x)]);
  const noise = model.noise.map((x) => [x.id, x.category || "", typeof x.scope === "string" ? x.scope : JSON.stringify(x.scope || {}), x.reason || ""]);
  return `# Доказательная база: ${esc(model.target)}\n\n${section("Подтверждённые выводы", "выводы и их evidence-ссылки", "обеспечивает трассируемость итоговых утверждений", ["ID", "Роль", "Результат", "Следствие", "Доказательства"], usages)}\n${section("Проверенное отсутствие использования", "проверки отсутствия", "отделяет подтверждённое отсутствие от неизвестности", ["ID", "Ожидаемые имена", "Основание", "Область", "Результат", "Следствие", "Доказательства"], absence)}\n${section("Эталонные подтверждения", "reference-only наблюдения", "не позволяет смешивать текущую реализацию с эталоном", ["ID", "Связь", "Следствие", "Доказательства"], references)}\n${section("Шум и исключения", "отфильтрованные нерелевантные области", "объясняет границы поиска", ["ID", "Категория", "Область", "Причина"], noise)}\n${section("Полный индекс источников", "конкретные исходные доказательства", "позволяет перейти от любого вывода к файлу и строке", ["ID", "Файл или область", "Строка", "Символ", "Результат"], evidence)}\n`;
}
function hashText(text) { return crypto.createHash("sha256").update(text).digest("hex"); }
function validateRenderedDocuments(model, documents) { const errors = []; const checks = [["decision-report.md", [...model.confirmedUsages, ...model.gaps]], ["implementation-map.md", [...model.recipientFamilies, ...model.criticalPaths]], ["evidence.md", [...model.evidenceIndex, ...model.checkedNoUsage]]]; for (const [name, rows] of checks) { const text = documents[name] || ""; for (const row of rows) if (!text.includes(row.id)) errors.push(`${name} is missing ${row.id}`); for (const label of ["Что показывает:", "Зачем нужна:", "Как читать:", "Как использовать:"]) if (!text.includes(label)) errors.push(`${name} is missing ${label}`); } return { ok: errors.length === 0, errors }; }
function run(model, outputDir, expectedDigest) { if (!expectedDigest) throw new Error("Stage 8 requires the digest recorded when Stage 7 closed"); if (model.integrity?.canonicalDigest !== expectedDigest) throw new Error(`Stage 8 input digest differs from closed Stage 7 digest: expected ${expectedDigest}, received ${model.integrity?.canonicalDigest || "missing"}`); const validation = validateReportModel(model); if (!validation.ok) throw new Error(`Stage 8 input validation failed: ${validation.errors.map((x) => `${x.path}: ${x.message}`).join("; ")}`); const documents = { "decision-report.md": renderDecision(model), "implementation-map.md": renderImplementation(model), "evidence.md": renderEvidence(model) }; const renderValidation = validateRenderedDocuments(model, documents); if (!renderValidation.ok) throw new Error(`Stage 8 render validation failed: ${renderValidation.errors.join("; ")}`); fs.mkdirSync(outputDir, { recursive: true }); for (const [name, content] of Object.entries(documents)) fs.writeFileSync(path.join(outputDir, name), content, "utf8"); const manifest = { schemaVersion: "1.0.0", stage: 8, status: "closed", input: { modelType: model.modelType, canonicalDigest: model.integrity.canonicalDigest }, validation: { stage7DigestBinding: "passed", model: "passed", render: "passed" }, outputs: Object.entries(documents).map(([name, content]) => ({ name, sha256: hashText(content) })).sort((a, b) => a.name.localeCompare(b.name)) }; fs.writeFileSync(path.join(outputDir, "manifest.json"), canonicalJson(manifest), "utf8"); return manifest; }
function main() { try { const args = process.argv.slice(2), get = (flag) => args[args.indexOf(flag) + 1], modelFile = get("--model"), output = get("--output-dir"), stateFile = get("--state"), explicitDigest = get("--expected-digest"); if (!modelFile || !output || (!stateFile && !explicitDigest)) throw new Error("Provide --model <report-model.json> --output-dir <directory> and --state <inventory-state.json> or --expected-digest <sha256>"); let expectedDigest = explicitDigest; if (stateFile) { const state = JSON.parse(fs.readFileSync(path.resolve(stateFile), "utf8")); if (state.lastCompletedStage !== 7 || state.currentStage !== 8 || !state.canonicalDigest) throw new Error("State does not record a closed Stage 7 canonical digest"); expectedDigest = state.canonicalDigest; } const manifest = run(JSON.parse(fs.readFileSync(path.resolve(modelFile), "utf8")), path.resolve(output), expectedDigest); process.stdout.write(`${JSON.stringify({ status: "closed", output: path.resolve(output), inputDigest: manifest.input.canonicalDigest, documents: manifest.outputs.length })}\n`); } catch (error) { process.stdout.write(`${JSON.stringify({ status: "blocked", errors: [{ message: error.message }] })}\n`); process.exitCode = 2; } }
if (require.main === module) main();
module.exports = { renderDecision, renderEvidence, renderImplementation, run, validateRenderedDocuments };
