"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),crypto=require("node:crypto");
const root=process.env.EVIDENCE_TEST_BASE || path.resolve(__dirname,"../../../..");
const {resolveChecks}=require(path.join(root,"shared/artifacts/src/canonical/checks.js"));
const {createCanonicalStageResult}=require(path.join(root,"shared/artifacts/src/canonical/result.js"));
function fixture(t) {const dir=fs.mkdtempSync(path.join(os.tmpdir(),"typed-checks-"));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.writeFileSync(path.join(dir,"owner.js"),"owner();\n");const scope={repositories:[{id:"repo",root:dir}]}, requirement={check:"verify owner",type:"source-confirmation",repository:"repo",file:"owner.js",line:1,claimRef:"ownership"}; const prior=createCanonicalStageResult({facts:{stage:2,status:"partial",repositoryScope:scope,openChecks:[requirement.check],summary:{checkRequirements:[requirement]}}}); const receipt={kind:"check-resolution",check:requirement.check,originDigest:prior.outputDigest,disposition:"checked",reason:"source read",evidenceRefs:["ev"]};const proof={id:"ev",status:"source-confirmed",repository:"repo",file:"owner.js",line:1,endLine:1,sourceFragment:"owner();",sourceHash:crypto.createHash("sha256").update(fs.readFileSync(path.join(dir,"owner.js"))).digest("hex"),claimRef:"ownership"};return {dir,scope,requirement,prior,receipt,proof};}
test("typed source blocker rejects candidate and unrelated source proof",t=>{const f=fixture(t);for(const proof of [{...f.proof,status:"candidate"},{...f.proof,file:"other.js"},{...f.proof,claimRef:"other"}])assert.throws(()=>resolveChecks(f.prior,{},[f.receipt],[proof],f.scope),/source-confirmation/);});
test("typed source blocker accepts fresh matching proof and survives omission",t=>{const f=fixture(t);const pending=resolveChecks(f.prior,{},[],[],f.scope);assert.deepEqual(pending.summary.checkRequirements,[f.requirement]);const resolved=resolveChecks(f.prior,{stage:2,status:"closed"},[f.receipt],[f.proof],f.scope);assert.deepEqual(resolved.openChecks,[]);assert.deepEqual(resolved.summary.checkRequirements,[f.requirement]);});
test("typed blocker context cannot be weakened on retry",t=>{const f=fixture(t);assert.throws(()=>resolveChecks(f.prior,{checkRequirements:[{...f.requirement,file:"other.js"}]},[],[],f.scope),/checkRequirements|weaken|context/);});
test("source obligation cannot be corrected into a product gap",t=>{const f=fixture(t);assert.throws(()=>resolveChecks(f.prior,{canonicalFacts:[{kind:"gap",id:"gap"}]},[{...f.receipt,disposition:"corrected",correctionRef:"gap"}],[],f.scope),/source-confirmation/);});
test("technical blocker correction requires an actual gap or limitation",()=>{const prior=createCanonicalStageResult({facts:{stage:2,status:"partial",openChecks:["product gap"]}});const receipt={kind:"check-resolution",check:"product gap",originDigest:prior.outputDigest,reason:"investigation complete; product behavior absent",disposition:"corrected",correctionRef:"gap"};const result=resolveChecks(prior,{canonicalFacts:[{kind:"gap",id:"gap",status:"confirmed"}]},[receipt],[],{});assert.deepEqual(result.openChecks,[]);assert.throws(()=>resolveChecks(prior,{},[receipt],[],{}),/correctionRef/);});
test("new typed check declaration is serialized in summary",()=>{const requirement={check:"owner",type:"source-confirmation",repository:"repo",file:"owner.js"};const result=createCanonicalStageResult({facts:{stage:1,status:"partial",openChecks:["owner"],checkRequirements:[requirement]}});assert.deepEqual(result.summary.checkRequirements,[requirement]);});

test("saved receipt proof is verified after serialization, including fresh source hash",t=>{const f=fixture(t),{writeStageArtifact}=require(path.join(root,"shared/artifacts/src/stage_artifact_v4.js")),{validateReceiptEvidence}=require(path.join(root,"shared/artifacts/src/canonical/receipt_evidence.js"));const facts=resolveChecks(f.prior,{stage:2,status:"closed",repositoryScope:f.scope,canonicalEvidence:[f.proof]},[f.receipt],[f.proof],f.scope);const written=writeStageArtifact({outputDir:path.join(f.dir,"artifact"),facts});const canonical=JSON.parse(fs.readFileSync(written.resultFile,"utf8"));assert.doesNotThrow(()=>validateReceiptEvidence(canonical,written.resultFile));fs.writeFileSync(path.join(f.dir,"owner.js"),"changed();\n");assert.throws(()=>validateReceiptEvidence(canonical,written.resultFile),/source-confirmation/);});
test("canonical structural validator rejects missing correction target",()=>{const {validateCanonicalStageResult}=require(path.join(root,"shared/artifacts/src/canonical/validation.js"));const receipt={kind:"check-resolution",check:"gap",originDigest:"a".repeat(64),disposition:"corrected",reason:"gap is product finding",correctionRef:"missing"};const canonical=createCanonicalStageResult({facts:{stage:2,status:"closed",canonicalFacts:[receipt]}});assert.match(validateCanonicalStageResult(canonical).errors.join(";"),/correctionRef/);});
test("early evidence diagnostics block canonical closure",()=>{const {validateCanonicalStageResult}=require(path.join(root,"shared/artifacts/src/canonical/validation.js"));const canonical=createCanonicalStageResult({facts:{stage:2,status:"closed",evidenceDiagnostics:[{code:"source-anchor",message:"exact lines differ"}]}});assert.equal(canonical.summary.closure.ok,false);assert.equal(validateCanonicalStageResult(canonical).ok,false);});

test("saved partial history forbids dropping typed context after resolution",t=>{const f=fixture(t),{writeStageArtifact}=require(path.join(root,"shared/artifacts/src/stage_artifact_v4.js")),{validateCheckHistory}=require(path.join(root,"shared/artifacts/src/canonical/lineage.js"));const partial=writeStageArtifact({outputDir:path.join(f.dir,"partial"),facts:{stage:2,status:"partial",repositoryScope:f.scope,openChecks:[f.requirement.check],checkRequirements:[f.requirement]}});const receipt={...f.receipt,originDigest:partial.canonical.outputDigest};const facts=resolveChecks(partial.canonical,{stage:2,status:"closed",repositoryScope:f.scope,canonicalEvidence:[f.proof],summary:{checkHistory:[{artifact:partial.resultFile,outputDigest:partial.canonical.outputDigest}]}},[receipt],[f.proof],f.scope);const canonical=createCanonicalStageResult({facts});assert.doesNotThrow(()=>validateCheckHistory(canonical));delete canonical.summary.checkRequirements;assert.throws(()=>validateCheckHistory(canonical),/context disappeared/);});
