"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),crypto=require("node:crypto");
const {main}=require("../src/stage_state");
const {createCanonicalStageResult}=require("../../shared/artifacts/src/canonical/result");
const {buildLineageFromPrevious}=require("../../shared/artifacts/src/canonical/lineage");
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"revision-state-")),state=path.join(root,"state.json"),scope={repositories:[{id:"repo",root,role:"source"}]};main(["init","--state",state]);const artifacts=[];for(let stage=0;stage<3;stage++){const artifact=path.join(root,`stage-${stage}.json`);fs.writeFileSync(artifact,JSON.stringify(createCanonicalStageResult({facts:{stage,status:"closed",repositoryScope:scope,summary:{lineage:stage?buildLineageFromPrevious(artifacts.at(-1),stage,scope):[]}}})));main(["advance","--state",state,"--stage",String(stage),"--artifact",artifact]);artifacts.push(artifact);}return {root,state,scope,artifacts};}
function revise(data,output,stage="1",extra=[]){return main(["revise","--state",data.state,"--stage",stage,"--output-state",output,"--reason","Include native ownership",...extra]);}
test("explicit revision creates a new state retaining exact predecessors and immutable originals",()=>{const data=fixture();try{const before=new Map([data.state,...data.artifacts].map(file=>[file,fs.readFileSync(file)]));const output=path.join(data.root,"revision.json");const result=revise(data,output);const state=JSON.parse(fs.readFileSync(output));assert.equal(result.kind,"revision");assert.equal(state.currentStage,1);assert.equal(state.lastCompletedStage,0);assert.equal(state.canonicalArtifact,data.artifacts[0]);assert.deepEqual(state.activeArtifacts.map(item=>item.artifact),[data.artifacts[0]]);assert.equal(state.revision.sourceStateDigest,crypto.createHash("sha256").update(before.get(data.state)).digest("hex"));assert.equal(state.revision.sourceArtifact,data.artifacts[1]);assert.equal(state.revision.reason,"Include native ownership");for(const [file,bytes] of before)assert.deepEqual(fs.readFileSync(file),bytes);assert.throws(()=>main(["advance","--state",output,"--stage","1","--artifact",data.artifacts[1]]),/reissue|revision/i);}finally{fs.rmSync(data.root,{recursive:true,force:true});}});
test("invalid revision arguments and stale originals never create destination state",()=>{const data=fixture();try{const before=fs.readFileSync(data.state);const output=path.join(data.root,"never-created","state.json");for(const argv of [["revise","--state",data.state,"--stage","1","--reason","why"],["revise","--state",data.state,"--stage","1","--output-state",output], ["revise","--state",data.state,"--stage","8","--output-state",output,"--reason","why"]])assert.throws(()=>main(argv));assert.throws(()=>revise(data,data.state),/exists|different/);fs.appendFileSync(data.artifacts[0],"invalid");assert.throws(()=>revise(data,output));assert.equal(fs.existsSync(path.dirname(output)),false);assert.deepEqual(fs.readFileSync(data.state),before);}finally{fs.rmSync(data.root,{recursive:true,force:true});}});
test("revision reissues requested and downstream artifacts through the public CLI",()=>{const data=fixture();try{const {spawnSync}=require("node:child_process");const output=path.join(data.root,"new state.json");const cli=path.resolve(__dirname,"../../index.js");const result=spawnSync(process.execPath,[cli,"stage_state","revise","--state",data.state,"--stage","1","--output-state",output,"--reason","Include native ownership"],{encoding:"utf8"});assert.equal(result.status,0,result.stdout+result.stderr);assert.equal(JSON.parse(result.stdout).currentStage,1);const revised1=path.join(data.root,"revised-1.json");fs.writeFileSync(revised1,JSON.stringify(createCanonicalStageResult({facts:{stage:1,status:"closed",repositoryScope:data.scope,summary:{target:"revised findings",lineage:buildLineageFromPrevious(data.artifacts[0],1,data.scope)}}})));main(["advance","--state",output,"--stage","1","--artifact",revised1]);assert.throws(()=>main(["advance","--state",output,"--stage","2","--artifact",data.artifacts[2]]),/reissue|revision/);const revised2=path.join(data.root,"revised-2.json");fs.writeFileSync(revised2,JSON.stringify(createCanonicalStageResult({facts:{stage:2,status:"closed",repositoryScope:data.scope,summary:{lineage:buildLineageFromPrevious(revised1,2,data.scope)}}})));const advanced=main(["advance","--state",output,"--stage","2","--artifact",revised2]);assert.equal(advanced.currentStage,3);assert.equal(advanced.revision.sourceState,data.state);}finally{fs.rmSync(data.root,{recursive:true,force:true});}});
test("Stage0 revision retains no predecessor and rejects duplicate destination",()=>{const data=fixture();try{const output=path.join(data.root,"revision-zero.json");revise(data,output,"0");const before=fs.readFileSync(output);const next=JSON.parse(before);assert.equal(next.currentStage,0);assert.equal(next.canonicalArtifact,null);assert.deepEqual(next.activeArtifacts,[]);assert.throws(()=>revise(data,output,"0"),/non-existing/);assert.deepEqual(fs.readFileSync(output),before);}finally{fs.rmSync(data.root,{recursive:true,force:true});}});
