"use strict";
const assert = require("node:assert/strict"), crypto = require("node:crypto"), fs = require("node:fs"), os = require("node:os"), path = require("node:path"), test = require("node:test"); const { canonicalizeStage2Candidates } = require("../../src/canonicalization/canonicalize.js");
function repository() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "stage2-evidence-")); const file = path.join(root, "source", "component.js"); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, "const feature = true;\n"); return { root, file, hash: crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"), scope: { repositories: [{ id: "repository-a", root, role: "source" }] } }; }
test("stage 2 canonicalization applies only caller-declared exclusions", () => { const base = { repository: "repository-a", file: "src/component.js", symbol: "FeatureContainer", line: 10, usageKind: "field-read", excerpt: "x.value" }; const result = canonicalizeStage2Candidates([{ ...base, matchedTerm: "feature" }, { ...base, matchedTerm: "targetFeature" }, { ...base, file: "ignored/component.js", matchedTerm: "feature" }], { exclusions: ["ignored"] }); assert.equal(result.evidence.length, 1); assert.deepEqual(result.evidence[0].matchedTerms, ["feature", "targetFeature"]); assert.equal(result.metrics.duplicatesRemoved, 1); assert.equal(result.metrics.noiseRemoved, 1); });
test("different usage kinds at one range remain distinct", () => { const base = { file: "src/component.js", symbol: "FeatureContainer", line: 10 }; assert.equal(canonicalizeStage2Candidates([{ ...base, usageKind: "field-read" }, { ...base, usageKind: "field-write" }]).evidence.length, 2); });
test("high-fanout duplicate corpus shrinks by at least 80 percent without merging usage kinds", () => { const candidates = []; for (let index = 0; index < 10000; index += 1) candidates.push({ repository: "repository-a", file: `source/file-${index % 100}.js`, symbol: "FeatureContainer", line: index % 100, usageKind: index % 2 ? "field-read" : "field-write", matchedTerm: `term-${index % 7}` }); for (let index = 0; index < 773; index += 1) candidates.push({ file: `ignored/file-${index}.js`, symbol: "FeatureContainer", line: index, usageKind: "source-text" }); const result = canonicalizeStage2Candidates(candidates, { exclusions: ["ignored"] }); assert.ok(result.evidence.length <= candidates.length * 0.2); assert.equal(result.metrics.candidatesFound, 10773); assert.equal(result.metrics.noiseRemoved, 773); assert.ok(result.evidence.some((item) => item.usageKind === "field-read")); assert.ok(result.evidence.some((item) => item.usageKind === "field-write")); });
test("candidate promotion recomputes full-file sha256 inside the exact declared repository", () => { const repo = repository(); const base = { repository: "repository-a", file: "source/component.js", line: 1, endLine: 1, sourceFragment: "const feature = true;", usageKind: "field-read" }; const confirmed = canonicalizeStage2Candidates([{ ...base, confirmation: { status: "source-confirmed", evidenceRefs: ["source-1"], sourceHash: repo.hash } }], { repositoryScope: repo.scope }).evidence[0]; assert.equal(confirmed.confirmation.status, "source-confirmed"); assert.equal(confirmed.confirmation.sourceHash, repo.hash); });
test("candidate promotion rejects stale hashes, undeclared repositories, and files outside root", () => { const repo = repository(); const confirmation = { status: "source-confirmed", evidenceRefs: ["source-1"], sourceHash: "a".repeat(64) }; const stale = canonicalizeStage2Candidates([{ repository: "repository-a", file: "source/component.js", confirmation }], { repositoryScope: repo.scope }).evidence[0]; const undeclared = canonicalizeStage2Candidates([{ repository: "repository-b", file: "source/component.js", confirmation: { ...confirmation, sourceHash: repo.hash } }], { repositoryScope: repo.scope }).evidence[0]; const outside = canonicalizeStage2Candidates([{ repository: "repository-a", file: path.join(repo.root, "..", "outside.js"), confirmation: { ...confirmation, sourceHash: repo.hash } }], { repositoryScope: repo.scope }).evidence[0]; assert.equal(stale.confirmation.status, "candidate"); assert.equal(undeclared.confirmation.status, "candidate"); assert.equal(outside.confirmation.status, "candidate"); });
test("candidate promotion rejects a physical escape through a junction", () => { const repo = repository(); const outside = fs.mkdtempSync(path.join(os.tmpdir(), "stage2-outside-")); const file = path.join(outside, "a.js"); fs.writeFileSync(file, "const escaped = true;\n"); const link = path.join(repo.root, "linked"); fs.symlinkSync(outside, link, "junction"); const sourceHash = crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); const row = canonicalizeStage2Candidates([{ repository: "repository-a", file: "linked/a.js", confirmation: { status: "source-confirmed", evidenceRefs: ["source-1"], sourceHash } }], { repositoryScope: repo.scope }).evidence[0]; assert.equal(row.confirmation.status, "candidate"); });
test("legacy confirmation cannot acquire a fragment from a snippet or current source", () => {
  const repo = repository();
  const base = { repository: "repository-a", file: "source/component.js", line: 1, endLine: 1, excerpt: "const feature = true;", confirmation: { status: "source-confirmed", evidenceRefs: ["source-1"], sourceHash: repo.hash } };
  assert.equal(canonicalizeStage2Candidates([base], { repositoryScope: repo.scope }).evidence[0].confirmation.status, "candidate");
  assert.equal(canonicalizeStage2Candidates([{...base, sourceFragment: "wrong"}], { repositoryScope: repo.scope }).evidence[0].confirmation.status, "candidate");
});
test("source adapter and repeated canonicalization preserve exact confirmed multiline anchors", () => {
  const repo = repository(), { candidatesFromSourceEvidence } = require("../../src/canonicalization/candidate_adapters.js");
  const sourceFragment = "\tconst λ = 1;  \nreturn λ;";
  fs.writeFileSync(repo.file, `${sourceFragment}\n`);
  const confirmation = { status: "source-confirmed", evidenceRefs: ["source-1"], sourceHash: crypto.createHash("sha256").update(fs.readFileSync(repo.file)).digest("hex") };
  const candidates = candidatesFromSourceEvidence({ checks: [{ matches: [{repository: "repository-a", file: "source/component.js", line: 1, endLine: 2, sourceFragment, confirmation}] }] });
  const first = canonicalizeStage2Candidates(candidates, { repositoryScope: repo.scope }).evidence;
  assert.equal(first[0].confirmation.status, "source-confirmed");
  assert.equal(first[0].confirmation.sourceFragment, sourceFragment);
  assert.equal(first[0].range.endLine, 2);
  assert.deepEqual(canonicalizeStage2Candidates(first, {repositoryScope: repo.scope}).evidence[0].confirmation, first[0].confirmation);
});
