"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const crypto = require("node:crypto");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { normalizeReportModel } = require("../../src/model/normalization.js");
const { validateReportModel } = require("../../src/model/validation.js");
function fixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "report-model-")); const file = path.join(root, "a.js"); fs.writeFileSync(file, "const x = true;\n"); const sourceHash = crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); return { root, sourceHash }; }
function model() { const { root, sourceHash } = fixture(); return normalizeReportModel({ target: "X", scope: { repositories: [{ id: "repository-a", root, role: "source" }] }, capabilities: [{ id: "ownership", status: "confirmed", evidenceRefs: ["ev-1"] }], evidenceIndex: [{ id: "ev-1", status: "source-confirmed", repository: "repository-a", file: "a.js", line: 1, endLine: 1, sourceFragment: "const x = true;", sourceHash }], confirmedUsages: [{ id: "use-1", evidenceRefs: ["ev-1"] }], checkedNoUsage: [], transition: { "next stage": "8" } }); }
test("model validator accepts canonical model", () => assert.equal(validateReportModel(model()).ok, true));
test("model normalization accepts canonical Stage 2 confirmation fields", () => {
  const { root, sourceHash } = fixture();
  const value = normalizeReportModel({ target: "X", scope: { repositories: [{ id: "repository-a", root, role: "source" }] }, capabilities: [{ id: "ownership", status: "confirmed", evidenceRefs: ["ev-1"] }], evidenceIndex: [{ id: "ev-1", repository: "repository-a", file: "a.js", confirmation: { status: "source-confirmed", sourceHash, line: 1, endLine: 1, sourceFragment: "const x = true;" } }], confirmedUsages: [{ id: "use-1", evidenceRefs: ["ev-1"] }], transition: { "next stage": "8" } });
  assert.equal(value.evidenceIndex[0].status, "source-confirmed");
  assert.equal(value.evidenceIndex[0].sourceHash, sourceHash);
  assert.equal(validateReportModel(value).ok, true);
});
test("model validator rejects broken evidence references", () => { const value = model(); value.confirmedUsages[0].evidenceRefs = ["missing"]; assert.equal(validateReportModel(value).errors.some((x) => x.code === "broken-ref"), true); });
test("model validator detects mutation through digest", () => { const value = model(); value.target = "changed"; assert.equal(validateReportModel(value).errors.some((x) => x.code === "integrity"), true); });
test("confirmed claims reject candidate, stale, and out-of-scope evidence", () => { const candidate = model(); candidate.evidenceIndex[0].status = "candidate"; candidate.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(candidate)); assert.equal(validateReportModel(candidate).errors.some((x) => x.code === "source-evidence"), true); const stale = model(); stale.evidenceIndex[0].sourceHash = "a".repeat(64); stale.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(stale)); assert.equal(validateReportModel(stale).errors.some((x) => x.code === "stale-evidence"), true); const outside = model(); outside.evidenceIndex[0].file = path.join(outside.scope.repositories[0].root, "..", "outside.js"); outside.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(outside)); assert.equal(validateReportModel(outside).errors.some((x) => x.code === "evidence-scope"), true); });
test("checked-no-usage requires a complete absence protocol and matching absence evidence", () => { const value = model(); value.checkedNoUsage = [{ id: "absence-1", status: "checked-no-usage", expectedNames: ["setX"], reason: "expected peer API", repository: "repository-a", searchScope: "src", performedChecks: ["text", "AST"], ordersChecked: ["second", "third"], linkingMethodsChecked: ["factory"], resultComplete: true, resultTruncated: false, consequence: "export path remains closed", evidenceRefs: ["ev-absence"] }]; value.evidenceIndex.push({ id: "ev-absence", status: "checked-no-usage", evidenceKind: "absence", repository: "repository-a", searchScope: "src", expectedNames: ["setX"], reason: "expected peer API", performedChecks: ["text", "AST"], ordersChecked: ["second", "third"], linkingMethodsChecked: ["factory"], resultComplete: true, resultTruncated: false, consequence: "export path remains closed", evidenceRefs: ["ev-absence"] }); value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.equal(validateReportModel(value).ok, true); value.evidenceIndex.find((row) => row.id === "ev-absence").performedChecks = ["text"]; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.equal(validateReportModel(value).errors.some((x) => x.code === "absence-evidence"), true); delete value.checkedNoUsage[0].reason; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.equal(validateReportModel(value).errors.some((x) => x.code === "absence-contract"), true); });
test("published report model schema is valid JSON", () => { const schema = JSON.parse(fs.readFileSync(path.resolve(require("node:path").resolve(__dirname, "../../../.."), "..", "references", "report-model.schema.json"), "utf8")); assert.equal(schema.$id, "inventory-report-model/2.0.0"); });
test("runtime requires the repository role declared by the schema", () => { const value = model(); delete value.scope.repositories[0].role; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.equal(validateReportModel(value).errors.some((x) => x.path.endsWith(".role")), true); });
test("checked-no-usage capability cannot bypass the full absence protocol", () => { assert.throws(() => normalizeReportModel({ target: "X", scope: { repositories: [{ id: "repository-a", root: fixture().root, role: "source" }] }, capabilities: [{ id: "input", status: "checked-no-usage", expectedNames: ["setX"], checkedScope: "src" }] }), /complete absence protocol/); });
test("model rejects a physical evidence escape through a junction", () => { const declared = fs.mkdtempSync(path.join(os.tmpdir(), "report-declared-")), outside = fs.mkdtempSync(path.join(os.tmpdir(), "report-outside-")), file = path.join(outside, "a.js"); fs.writeFileSync(file, "const escaped = true;\n"); fs.symlinkSync(outside, path.join(declared, "linked"), "junction"); const sourceHash = crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); const value = normalizeReportModel({ target: "X", scope: { repositories: [{ id: "repository-a", root: declared, role: "source" }] }, capabilities: [{ id: "ownership", status: "confirmed", evidenceRefs: ["ev-1"] }], evidenceIndex: [{ id: "ev-1", status: "source-confirmed", repository: "repository-a", file: "linked/a.js", sourceHash }], confirmedUsages: [{ id: "use-1", evidenceRefs: ["ev-1"] }], transition: { "next stage": "8" } }); assert.equal(validateReportModel(value).errors.some((x) => x.code === "evidence-scope"), true); });
test("source-confirmed implementation entry still requires current source-confirmed evidence", () => { const value = model(); value.implementationEntryPoints = [{ id: "entry-1", status: "source-confirmed", evidenceRefs: ["ev-candidate"], capabilityRefs: ["ownership"] }]; value.evidenceIndex.push({ id: "ev-candidate", status: "candidate", repository: "repository-a", file: "missing.js", sourceHash: "0".repeat(64) }); value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.equal(validateReportModel(value).errors.some((x) => x.code === "source-evidence"), true); });
test("optional source-confirmed capability still requires current source-confirmed evidence", () => { const value = model(); value.capabilities.push({ id: "reference", status: "source-confirmed", requiredForFinalReport: false, evidenceRefs: ["ev-candidate"] }); value.evidenceIndex.push({ id: "ev-candidate", status: "candidate", repository: "repository-a", file: "missing.js", sourceHash: "0".repeat(64) }); value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.equal(validateReportModel(value).errors.some((x) => x.code === "source-evidence" && x.path.startsWith("capabilities")), true); });
test("runtime enforces top-level required and additionalProperties schema rules", () => { const value = model(); delete value.coverage; value.unpublishedField = true; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); const codes = validateReportModel(value).errors.map((x) => x.code); assert.ok(codes.includes("required")); assert.ok(codes.includes("additional-property")); });
test("generic absence requires matching evidence and required capability cannot remain unchecked", () => { const value = model(), protocol = { status: "checked-no-usage", expectedNames: ["setX"], reason: "peer API", repository: "repository-a", searchScope: "src", performedChecks: ["text"], ordersChecked: ["N/A"], linkingMethodsChecked: ["N/A"], resultComplete: true, resultTruncated: false, consequence: "path absent", evidenceRefs: [] }; value.ownership = [{ id: "owner-absence", ...protocol }]; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.ok(validateReportModel(value).errors.some((x) => x.code === "absence-evidence")); const unchecked = model(); unchecked.capabilities[0].status = "unchecked"; unchecked.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(unchecked)); assert.ok(validateReportModel(unchecked).errors.some((x) => x.code === "capability-open")); });
test("runtime rejects additional integrity properties", () => { const value = model(); value.integrity.unpublished = true; assert.ok(validateReportModel(value).errors.some((x) => x.code === "integrity-schema")); });
test("runtime enforces decision and transition schema enums", () => { const value = model(); value.decisionStatus = "bogus"; value.transition["next stage"] = 8; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); const codes = validateReportModel(value).errors.map((x) => x.code); assert.ok(codes.includes("decision-status")); assert.ok(codes.includes("transition")); });
test("confirmed planning claims require source-confirmed evidence", () => { const value = model(); value.ownership = [{ id: "owner", status: "confirmed", evidenceRefs: ["ev-candidate"] }]; value.evidenceIndex.push({ id: "ev-candidate", status: "candidate", repository: "repository-a" }); value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.ok(validateReportModel(value).errors.some((x) => x.code === "source-evidence")); });
test("terminal model requires at least one required capability", () => { const value = model(); value.capabilities = [{ id: "reference", status: "reference-only", requiredForFinalReport: false }]; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.ok(validateReportModel(value).errors.some((x) => x.code === "capability-terminal")); });
test("confirmed planning claims cannot omit evidence", () => { const value = model(); value.ownership = [{ id: "owner", status: "source-confirmed" }]; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.ok(validateReportModel(value).errors.some((x) => x.code === "source-evidence")); });
test("candidate planning rows may keep unresolved evidence selectors", () => { const value = model(); value.scenarios = [{ id: "scenario-candidate", status: "candidate", evidenceRefs: ["ev-pending"] }]; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.equal(validateReportModel(value).errors.some((x) => x.code === "broken-ref" && x.path.includes("scenarios")), false); });
test("terminal capability marker must remain explicit", () => { const value = model(); delete value.capabilities[0].requiredForFinalReport; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); assert.ok(validateReportModel(value).errors.some((x) => x.code === "capability-terminal")); });
test("runtime enforces published model scalar and object types", () => { const value = model(); value.inventoryId = ""; value.provenance = "not-an-object"; value.executiveSummary = []; value.openChecks = [7, 7]; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); const errors = validateReportModel(value).errors; assert.ok(errors.some((x) => x.path === "inventoryId")); assert.ok(errors.some((x) => x.path === "provenance")); assert.ok(errors.some((x) => x.path === "executiveSummary")); assert.ok(errors.some((x) => x.path === "openChecks")); });
test("runtime enforces published absence item types and uniqueness", () => { const value = model(), absence = { id: "absence", status: "checked-no-usage", expectedNames: ["setX", "setX"], reason: 7, repository: "repository-a", searchScope: "src", performedChecks: ["text"], ordersChecked: ["N/A"], linkingMethodsChecked: ["N/A"], resultComplete: true, resultTruncated: false, consequence: "absent", evidenceRefs: ["ev-absence"] }; value.checkedNoUsage = [absence]; value.evidenceIndex.push({ ...absence, id: "ev-absence", evidenceKind: "absence", evidenceRefs: [] }); value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); const errors = validateReportModel(value).errors; assert.ok(errors.some((x) => x.path.endsWith("expectedNames") && x.code === "unique")); assert.ok(errors.some((x) => x.path.endsWith("reason") && x.code === "absence-contract")); });
test("runtime enforces checkedNoUsage status and standalone absence evidence schema", () => { const value = model(), protocol = { status: "checked-no-usage", expectedNames: ["setX"], reason: "peer API", repository: "repository-a", searchScope: "src", performedChecks: ["text"], ordersChecked: ["N/A"], linkingMethodsChecked: ["N/A"], resultComplete: true, resultTruncated: false, consequence: "absent", evidenceRefs: ["ev-absence"] }; value.checkedNoUsage = [{ id: "absence", ...protocol, status: "candidate" }]; value.evidenceIndex.push({ id: "ev-absence", status: "checked-no-usage", evidenceRefs: ["ev-absence"] }); value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); const errors = validateReportModel(value).errors; assert.ok(errors.some((x) => x.path.endsWith(".status") && x.code === "absence-contract")); assert.ok(errors.some((x) => x.path.startsWith("evidenceIndex") && x.code === "absence-contract")); });
test("runtime resolves capability and typed planning references", () => { const value = model(); value.capabilities.push({ id: "reference", status: "not-applicable", requiredForFinalReport: false, evidenceRefs: ["missing-evidence"] }); value.criticalPaths = [{ id: "path", status: "not-applicable", scenarioRefs: ["missing-scenario"], testSurfaceRefs: ["missing-test"] }]; value.integrity.canonicalDigest = require("../../src/model/serialization.js").digest(require("../../src/model/serialization.js").withoutIntegrity(value)); const paths = validateReportModel(value).errors.filter((x) => x.code === "broken-ref").map((x) => x.path); assert.ok(paths.some((x) => x.startsWith("capabilities"))); assert.ok(paths.some((x) => x.endsWith("scenarioRefs"))); assert.ok(paths.some((x) => x.endsWith("testSurfaceRefs"))); });
test("unreferenced source-confirmed evidence also requires current exact anchors", () => {
    const value = model();
    value.evidenceIndex.push({...value.evidenceIndex[0], id: "ev-orphan", line: 999, endLine: 999});
    value.integrity = normalizeReportModel(value).integrity;
    assert.equal(validateReportModel(value).ok, false);
});
test("shared evidence is read once per model validation and duplicate IDs remain invalid", (t) => {
    const value = model(), original = fs.readFileSync;
    let sourceReads = 0;
    t.mock.method(fs, "readFileSync", (...args) => { if (path.basename(String(args[0])) === "a.js") sourceReads += 1; return original(...args); });
    assert.equal(validateReportModel(value).ok, true);
    assert.equal(sourceReads, 1);
    value.evidenceIndex.push({...value.evidenceIndex[0]});
    value.integrity = normalizeReportModel(value).integrity;
    assert.ok(validateReportModel(value).errors.some((error) => error.code === "duplicate-id"));
});

test("declared coverage blocks RRZA-shaped incomplete lifecycle despite confirmed decision", () => {
 const value=model(); value.coverage={status:"partial",profile:{requiredCollections:["dictionary","criticalPaths"],requiredCriticalPaths:["open","save","cancel"],notApplicable:{},notApplicableCriticalPaths:{}}};
 const result=validateReportModel(normalizeReportModel(value)); assert.ok(result.errors.some(x=>x.code==="research-incomplete"));assert.ok(result.errors.some(x=>x.code==="coverage-required"));assert.ok(result.errors.some(x=>x.code==="critical-path-required"));
});
test("complete research permits a proven product gap and justified nonapplicability", () => {
 const value=model();value.coverage={status:"complete",profile:{requiredCollections:["dictionary","criticalPaths"],notApplicable:{dictionary:"No name transitions in this task"},requiredCriticalPaths:["save","cancel"],notApplicableCriticalPaths:{cancel:"Operation cannot be cancelled"}}};
 value.criticalPaths=[{id:"save-path",coverageKey:"save",status:"confirmed",steps:["write data"],evidenceRefs:["ev-1"]}];value.gaps=[{id:"gap",category:"product-gap",status:"confirmed",expectedPath:"missing setter",evidenceRefs:["ev-1"]}];
 assert.equal(validateReportModel(normalizeReportModel(value)).ok,true);
 value.criticalPaths[0].status="candidate";assert.ok(validateReportModel(normalizeReportModel(value)).errors.some(x=>x.code==="critical-path-required"));
});

test("direct report rows normalize known intermediate categories without promoting proof",()=>{
 const value=model();value.gaps=[{id:"gap",status:"product-gap",statement:"Absent API",expectedPath:"setX"}];value.scenarios=[{id:"candidate",status:"matched"}];const normalized=normalizeReportModel(value);
 assert.equal(normalized.gaps[0].category,"product-gap");assert.equal(normalized.gaps[0].status,"unknown");assert.equal(normalized.scenarios[0].status,"candidate");
 assert.throws(()=>normalizeReportModel({...value,scenarios:[{id:"bad",status:"typo"}]}),/Unsupported.*status/);
});
test("coverage profile validates requirement names and N/A reasons",()=>{
 const {validateCoverageProfile}=require("../../src/model/coverage.js");
 assert.equal(validateCoverageProfile({requiredCollections:[],notApplicable:{}}).ok,true);
 for(const value of [{requiredCollections:["bogus"]},{requiredCollections:["dictionary"],notApplicable:{dictionary:" "}},{requiredCriticalPaths:["save"],notApplicableCriticalPaths:{open:"irrelevant"}},{requiredCollections:"dictionary"}])assert.equal(validateCoverageProfile(value).ok,false);
});
test("coverage diagnostics tolerate malformed rows without throwing",()=>{
 const value=model();value.coverage={profile:{requiredCollections:["criticalPaths"],requiredCriticalPaths:["save"]}};value.criticalPaths=[null];assert.doesNotThrow(()=>validateReportModel(value));
});
test("model provenance retains typed confirmation obligations alongside receipts",()=>{
 const value=model();const checkRequirements=[{check:"verify save",type:"source-confirmation",repository:"repository-a",file:"a.js"}];
 assert.deepEqual(normalizeReportModel({...value,checkRequirements}).provenance.checkRequirements,checkRequirements);
});
